# Generated by Django 3.1 on 2020-08-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiclassS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.IntegerField()),
                ('lecturer', models.CharField(max_length=10)),
                ('class_room', models.CharField(max_length=10)),
                ('students_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AiStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('class_num', models.IntegerField()),
                ('sex', models.CharField(max_length=2)),
                ('phone_number', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=30)),
            ],
        ),
    ]
