# Generated by Django 3.1 on 2020-08-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AiInfoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AiclassS',
            new_name='Aiclass',
        ),
    ]
