# Generated by Django 3.1 on 2020-08-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AiInfoApp', '0002_auto_20200819_1545'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aiclass',
            new_name='classes',
        ),
    ]
