# Generated by Django 3.1 on 2020-08-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.IntegerField()),
                ('lecturer', models.CharField(max_length=10)),
                ('class_room_num', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AiStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=5)),
                ('phone_num', models.CharField(max_length=30)),
            ],
        ),
    ]
